version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-node
    # command: npx create-react-app app
    volumes:
      - ./devdir/:/usr/src/devdir/
    tty: true
    ports:
      - 3000:3000